layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: GraphQL
    web_url: https://graphql.org/
    image_url: https://graphql.org/img/logo.svg

  - name: Kubernetes
    web_url: https://kubernetes.io/
    image_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg

  - name: ArangoDB
    web_url: https://www.arangodb.com/
    image_url: https://www.arangodb.com/wp-content/uploads/2016/05/ArangoDB_logo_avocado_@1.png
