layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: GraphQL
    web_url: https://graphql.org/
    image_url: https://graphql.org/img/logo.svg

  - name: Kubernetes
    web_url: https://kubernetes.io/
    image_url: https://www.vectorlogo.zone/logos/kubernetes/kubernetes-icon.svg

  - name: ArangoDB
    web_url: https://www.arangodb.com/
    image_url: https://www.vectorlogo.zone/logos/arangodb/arangodb-icon.svg

repos:
  - html_url: https://github.com/AEB-labs/graphql-weaver
    owner:
      login: AEB-labs
    name: graphql-weaver
    description: A tool to combine, link and transform GraphQL schemas
    stargazers_count: 176
    forks_count: 13
  - html_url: https://github.com/AEB-labs/cruddl
    owner:
      login: AEB-labs
    name: cruddl
    description: Create a GraphQL API for your database, using the GraphQL SDL to model your schema.
    stargazers_count: 48
    forks_count: 4
  - html_url: https://github.com/vita-us/ViTA
    owner:
      login: vita-us
    name: ViTA
    description: Visual Text Analytics for Digital Humanities
    stargazers_count: 4
    forks_count: 0
    homepage: http://minuet.visus.uni-stuttgart.de/#/documents
  - html_url: https://github.com/clustercompare/clustercompare
    owner:
      login: clustercompare
    name: clustercompare
    description: Visual Comparison of Software Modularizations to Multiple Clustering Results
    stargazers_count: 2
    forks_count: 0
    homepage: https://clustercompare.jan-melcher.de/